### ISSUE TITLE
persisting settings from setting.tsx (e.g. FeatureService URL)

### ISSUE THREAD

**Issue by shawnmgoulet** [jccartwright/exb-widgets#1]
https://user-images.githubusercontent.com/3179974/186524891-a8fe5f33-6279-44fd-85d8-50a26e9fe1fa.mp4

@jccartwright are you not seeing this behavior on your end in regards to this issue?

**Comment by jccartwright** [comment]
yes, I see the value persisted in this.props.config.featureServiceUrl but if you open the settings panel after reloading the experience, the value does not appear in the TextInput

Do you have to explicitly look for the property and initialize the TextInput accordingly? (unlike the DataSourceSelector or MapWidgetSelector)

**Comment by shawnmgoulet** [comment]
Thanks for clarifying @jccartwright.

Below is a link to the comments on the code that I added to fix this. We use the `onChange` method from the `React.InputHTMLAttributes` Interface instead of the `onAcceptValue` method that's provided by the `text-input.d.ts` type.

https://github.com/jccartwright/exb-widgets/commit/861f233cf73a85f49d022c75d87898435d27c108#r82180906

**Comment by jccartwright** [comment]
Thanks Shawn, this works for me. Only thing I changed from your code was to type the onChange event, e.g.
`const onServiceUrlChange = (event: React.ChangeEvent<HTMLInputElement>) => {`
