### ISSUE TITLE
DataRecordsSelectionChange message only contains one of two features found

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#10]
When I have two layers visible and a mouse click retrieves a feature from each layer (i.e. popup shows 2 features), the DataRecordsSelectionChange message seems to only include one of the features at a time. Selecting the second feature in the popup causes a third message containing the corresponding feature displayed in the popup.

Is this the expected behavior? The [documentation](https://developers.arcgis.com/experience-builder/api-reference/jimu-core/DataRecordsSelectionChangeMessage) suggests that multiple features might be contained in the message. 

Less important, but curious is why two messages are received in response to the first mouse click - one with zero results, and a second containing one of the identified features.

<img width="1904" alt="Screen Shot 2022-09-01 at 4 39 48 PM" src="https://user-images.githubusercontent.com/918022/188025608-717b5342-9b55-4e8c-b375-f05cb25ddabe.png">

**Comment by shawnmgoulet** [comment]
As the documentation states, the properties of the message include `DataRecord[]`, which includes the `records`. I would have expected the message to include `DataRecordSet` instead, but regardless, looking through the code for the OOTB map widget, it's not clear if the `DataRecordsSelectionChange` message is even published as searching through it's code doesn't clarify it:

I do not see a `DatRecordsSelectionChange` message being published in these, so it's not clear to me it's even available from the Map widget.
![image](https://user-images.githubusercontent.com/3179974/188155072-91ba45e8-67b4-4e67-ae81-e3de629ccae0.png)

These are related to some actions. Again, not clear the message is being published via a record change within the map here.
![image](https://user-images.githubusercontent.com/3179974/188156552-c3feffd8-0f75-4faa-bbe0-19d704808db0.png)

I will have to clarify with Experience Builder team unless you see something differently.

**Comment by jccartwright** [comment]
Just based on what I'm seeing w/in the subscriber-demo [action handler](https://github.com/jccartwright/exb-widgets/blob/main/widgets/subscriber-demo/src/actions/message-handler-action.ts), it seems pretty clear that the map is publishing a DataRecordsSelectionChange message. I can give you a very quick demo this afternoon if you like.
