### ISSUE TITLE
custom icon for widget

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#12]
The [docs](https://developers.arcgis.com/experience-builder/guide/button-widget/) suggest that only PNG, GIF, JPG, JPEG, and BMP format images may be used as button icons in Builder. Is this correct?  Is there no way to use Calcite icons or jimu-icons in Builder?

I see an [example](https://developers.arcgis.com/experience-builder/guide/widget-ui/) of using jimu-icons in a custom button widget and the [use-calcite-components sample](https://github.com/Esri/arcgis-experience-builder-sdk-resources/blob/master/widgets/use-calcite-components/src/runtime/widget.tsx) uses a calcite icon in a custom button.

**Comment by shawnmgoulet** [comment]
Making use of the calcite component or jimu-icons in the button icons in the builder is not supported at this point.
