### ISSUE TITLE
data retrieved from store but not accessible in view's on click handler

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#14]
See [widget.tsx](https://github.com/jccartwright/exb-widgets/blob/main/widgets/h3-layer/src/runtime/widget.tsx) lines 53, 57. Data are visible when component runs but not within view click handler

**Comment by jccartwright** [comment]
Added a button and handler to [subscriber-demo](https://github.com/jccartwright/exb-widgets/blob/main/widgets/subscriber-demo/src/runtime/widget.tsx) (line 41) which demonstrates problem in a simpler context than h2-layer

**Comment by shawnmgoulet** [comment]
Looked into subscriber demo today. Tried a handful of alternative approaches and didn't sort it. Will reach out to the team on it.

**Comment by shawnmgoulet** [comment]
The code within the `onExecute` function's `MessageType.DataSourceFilterChange` case branch is specific to having the Filter widget configured against it. [Lines 44 and 45](https://github.com/jccartwright/exb-widgets/blob/main/widgets/subscriber-demo/src/actions/message-handler-action.ts#L44-L45) of `message-handler-action.ts` stand up a `const`, then use that `const` to execute the `appAction.widgetStatePropChange` API method. There we can obtain the `queryParams` through the change.

If you configure the Filter widget on the data source, then turn that on, you will see the query params in your UI's "Filter:" row and it will display in the alert message.

![image](https://user-images.githubusercontent.com/3179974/189699088-974f1e9e-5a98-44c0-ac64-1819b8503248.png)

**Comment by jccartwright** [comment]
created a new experience and the subscriber-demo appears to be correctly accessing the widgetState in an event handler.  The h3-layer is still not however. The widgetState.queryParams appear to be reset between line [58](https://github.com/jccartwright/exb-widgets/blob/d1be87128de4e0a19a91739ab2b62a30a5e219ac/widgets/h3-layer/src/runtime/widget.tsx#L58) and line [66](https://github.com/jccartwright/exb-widgets/blob/d1be87128de4e0a19a91739ab2b62a30a5e219ac/widgets/h3-layer/src/runtime/widget.tsx#L66). Either that or [displayHexbinSummary](https://github.com/jccartwright/exb-widgets/blob/d1be87128de4e0a19a91739ab2b62a30a5e219ac/widgets/h3-layer/src/runtime/widget.tsx#L65) is forming a closure over the original (empty) value and hiding the changed value.

**Comment by shawnmgoulet** [comment]
Your comment above is related to #7, yes?

Your comment on l62, do you mean l58? I'm seeing it logged in the `widgetState` object?
![image](https://user-images.githubusercontent.com/3179974/189751072-d50ae270-4231-4817-8817-b935c67e1662.png)

**Comment by jccartwright** [comment]
Yes, the 2 issues are related.  For the client-side layer (either feature or graphics) I need to be able to:
1) grab the attributes from the individual feature receiving the click
2) react to changes in the queryParams and have access to the current queryParams in the click handler.

The click handler needs both pieces of information to summarize the selected hexbin

It appears that the queryParams are always empty in the click handler. Not sure if that is because it is the initial state (i.e. when function defined) or whether the widgetState is getting reset somewhere between the component re-rendering on datasourcefilterchange and the click handler.

**Comment by jccartwright** [comment]
Just pushed a simple test to h3-layer where storing the widgetState.queryParams with useRef appears to work. Can’t really explain why though...

**Comment by jccartwright** [comment]
closing in favor of the more focused issue #23
