### ISSUE TITLE
retrieve child widgets used in widget.tsx from withing setting.tsx

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#19]
The control-the-widget-state example shows [retrieving a list of the child widgets](https://github.com/Esri/arcgis-experience-builder-sdk-resources/blob/7c912e0d11cdf4f2170b462db6457c51a73e2f3e/widgets/control-the-widget-state/src/runtime/widget.tsx#L47) but is there a way to retrieve the child widgets of the main widget from within settings.tsx? i.e. does the Widget and its Settings page have access to one another's appStore, e.g.
`        const widgets = getAppStore().getState().appConfig.widgets;
`

**Comment by shawnmgoulet** [comment]
If we add this code to a the h3 widget's `widget.tsx` and `setting.tsx`:
![image](https://user-images.githubusercontent.com/3179974/195428512-f628d124-dfee-4e1d-b8ee-75b53fdf6f4b.png)


we get this info reported to the console:
![image](https://user-images.githubusercontent.com/3179974/195427492-3161676a-3e2d-4c30-a9e7-9442ace2aa0f.png)

Therefore, the widgets retrieved from the appStore are different between the widget and the setting.
