### ISSUE TITLE
webMercatorUtils throws error in class implementing AbstractMessageAction

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#2]
Attempting to use webMercatorUtils, e.g.
`const geoExtent = webMercatorUtils.webMercatorToGeographic(extent, false) as Extent`

causes several errors like:
`Load module error. TypeError: window.require is not a function`

Just importing the module, e.g.
`import webMercatorUtils from 'esri/geometry/support/webMercatorUtils'

works OK. The webMercatorUtils.webMercatorToGeographic call works OK w/in the Widget itself. See full [source](https://github.com/jccartwright/exb-widgets/blob/main/subscriber-demo/src/actions/message-handler-action.ts) for context.

**Comment by shawnmgoulet** [comment]
@jccartwright which widget are you attempting to use `webMercatorUtils` within and do you see this error with the widget alone in an experience, or just with the widget + what other widget(s)?

**Comment by jccartwright** [comment]
I added an example to the [subscriber-demo](https://github.com/jccartwright/exb-widgets/blob/main/widgets/subscriber-demo/) but note that the problem only manifests in the AbstractMessageAction [implementation](https://github.com/jccartwright/exb-widgets/blob/main/widgets/subscriber-demo/src/actions/message-handler-action.ts), seems to work OK w/in the widget itself.

**Comment by shawnmgoulet** [comment]
@jccartwright I'm not seeing errors related to `webMercatorUtils`, but maybe I'm missing something here?

![image](https://user-images.githubusercontent.com/3179974/187273223-75b04a97-242e-4bad-91a3-7433e99a4e08.png)


![image](https://user-images.githubusercontent.com/3179974/187273254-53ee0ff4-5a40-424a-85f2-7c81b8376d55.png)

![image](https://user-images.githubusercontent.com/3179974/187273869-9d03a7a5-2845-4aea-8381-f7c60480eb8a.png)

**Comment by jccartwright** [comment]
Strange - I can reproduce the problem on both Chrome and Firefox (on the Mac)
<img width="605" alt="Screen Shot 2022-08-29 at 1 05 35 PM" src="https://user-images.githubusercontent.com/918022/187278439-e2a49567-ceaf-40f1-b3f9-5d4bdd3d20c8.png">
