### ISSUE TITLE
h3-layer unable to load 3rd party dependency

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#20]
Added [geobuckets](https://github.com/mtralka/GeoBuckets) dependency but is failing to [load](https://github.com/jccartwright/exb-widgets/blob/b2e50bd3006e01549e2ff26c2eaa55b5724d9ae0/widgets/h3-layer/src/Classification.ts#L1) one of it's dependencies:
`ERROR in ./exb-widgets/widgets/h3-layer/node_modules/geobuckets/dist/src/index.js 44:0-58
Module not found: Error: Can't resolve './utils' in '/Users/jcc/Applications/ArcGISExperienceBuilder/client/exb-widgets/widgets/h3-layer/node_modules/geobuckets/dist/src'
Did you mean 'utils.js'?
BREAKING CHANGE: The request './utils' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
resolve './utils' in '/Users/jcc/Applications/ArcGISExperienceBuilder/client/exb-widgets/widgets/h3-layer/node_modules/geobuckets/dist/src'
  using description file: /Users/jcc/Applications/ArcGISExperienceBuilder/client/exb-widgets/widgets/h3-layer/node_modules/geobuckets/package.json (relative path: ./dist/src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/jcc/Applications/ArcGISExperienceBuilder/client/exb-widgets/widgets/h3-layer/node_modules/geobuckets/package.json (relative path: ./dist/src/utils)
      Field 'browser' doesn't contain a valid alias configuration
      /Users/jcc/Applications/ArcGISExperienceBuilder/client/exb-widgets/widgets/h3-layer/node_modules/geobuckets/dist/src/utils doesn't exist
 @ ./exb-widgets/widgets/h3-layer/src/Classification.ts 10:0-45 44:38-53
 @ ./exb-widgets/widgets/h3-layer/src/h3-utils.ts 16:0-50 201:35-49
 @ ./exb-widgets/widgets/h3-layer/src/runtime/widget.tsx 35:0-113 70:33-49 75:25-44 102:8-21 106:8-23 123:46-57`

works in ESM so I'm guessing it's something about Webpack in the ExB environment.

**Comment by shawnmgoulet** [comment]
@jccartwright -for now it looks like you'll have to go into the `node_modules` and change the requested resources from, in this case, `.utils` to `./utils.js` (`<path-to-resource>/<resource-file>.js`).

There's a number of changes you'll need to make, but once I made those, here is what I'm seeing after compiling the widget successfully, adding to an experience, and selecting a hex bin:
![image](https://user-images.githubusercontent.com/3179974/194084007-12552e7b-f6fc-4c59-aec5-06bd3a4c07ad.png)

 I will inquire to see if there's a cleaner solution to update all at once. Let me know if you would like to jump on a screen share to walk through a few if this isn't clear enough.

**Comment by jccartwright** [comment]
Thanks for the quick reply. I was hoping it might just be some webpack configuration. I found that I can also just install the source directly into the widget directory.  Since I’ve got a couple workarounds now we can deprioritize this issue.

**Comment by shawnmgoulet** [comment]
@jccartwright when a lib's `package.json` has `"type": "module"` it must use `import {} from "<some>.js"` rather than `... from <some>` (or a `.cjs` extension). Geobuckets uses `import {} from <some>`, which yields the terminal errors.

https://nodejs.org/api/packages.html#type

**Comment by jccartwright** [comment]
closing issue as it appears to be a conflict with the way the author created the 3rd-party package and webpack. Work around is to install the source directly into the widget's src hierarchy and not use the NPM dependency. Note native ESM environments, e.g. Vite.js, don't exhibit the problem.
