### ISSUE TITLE
documentation for built-in CSS classes?

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#21]
The [arcgis-experience-builder-sdk-resources](https://github.com/Esri/arcgis-experience-builder-sdk-resources) sample widgets use a variety of CSS classes (e.g. [jimu-widget, p-2](https://github.com/Esri/arcgis-experience-builder-sdk-resources/blob/7c912e0d11cdf4f2170b462db6457c51a73e2f3e/widgets/add-layers/src/runtime/widget.tsx#L129)) for which I cannot find documentation.

**Comment by shawnmgoulet** [comment]
@jccartwright some documentation for CSS utility classes can be found [here](https://developers.arcgis.com/experience-builder/guide/widget-ui/#css-utility-classes). From the link above, as we were discussing yesterday as likely:
> `jimu-ui` provides the same CSS utility classes as Bootstrap (under the hood, Experience Builder uses Reactstrap)

The page does not discuss `jimu-` classes. I have inquired.

**Comment by shawnmgoulet** [comment]
@jccartwright from the Experience Builder team:
> The `jimu-<specific>` CSS classes are not documented yet.
