### ISSUE TITLE
way to programmatically select select View w/in a Section?

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#22]
Is there a way to programmatically select a specific view in a Section widget, either directly via the Section state or through the Views Navigation widget? (see screenshot). Somewhat analogous to the way in which the [control-the-widget-state](https://github.com/Esri/arcgis-experience-builder-sdk-resources/tree/master/widgets/control-the-widget-state/src/runtime) works for opening a sidepanel?

Investigating a possible workaround of programmatically triggering mouseclick event on link w/in Views Navigation widget.

<img width="1573" alt="Screen Shot 2022-10-11 at 2 45 22 PM" src="https://user-images.githubusercontent.com/918022/195194778-f14acd3c-069e-4da2-b40d-821f624ddb4e.png">

**Comment by shawnmgoulet** [comment]
@jccartwright I am not seeing an action key declared within the `ActionKeys` enum within `client\jimu-core\lib\app-actions.d.ts` for Views Navigation. Using an approach similar to the control the widget state sample, this is where we would expect it to be defined.

I have inquired to confirm that I'm not missing something on that and then also about recommended alternative(s).

**Comment by shawnmgoulet** [comment]
@jccartwright - from the team:

> You can call Jimu API to change the view:
`import {browserHistory} from 'jimu-core'`
 `browserHistory.changeView()`

**Comment by jccartwright** [comment]
thanks. I don't see that browserHistory function as available in jimu-core:

Module '"jimu-core"' has no exported member 'browserHistory'.ts(2305)

Any idea on what the parameters are?

**Comment by shawnmgoulet** [comment]
The `changeView` function within `client\jimu-core\lib\browser-history.d.ts` specifies `setionId: string, viewId: string`

**Comment by jccartwright** [comment]
Thanks. I'm getting the following error in the browser console when using browserHistory.changeView():

Uncaught (in promise) TypeError: jimu_core__WEBPACK_IMPORTED_MODULE_0__.browserHistory is undefined

**Comment by shawnmgoulet** [comment]
@jccartwright is this how you tried to implement? This is what I'm getting.

I am reaching out to the team. The suggested code above was directly from them.

![image](https://user-images.githubusercontent.com/3179974/196202238-91ac1227-0cfe-4b48-9452-2959822e6f15.png)

**Comment by jccartwright** [comment]
yes, see toggle-sidebar [widget](https://github.com/jccartwright/exb-widgets/blob/700abe74827a1e327c4b67070d7decba4858feb0/widgets/toggle-sidebar/src/runtime/widget.tsx#L95). Error is:

widget.tsx?446b:95 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'changeView')
    at eval (widget.tsx?446b:95:1)

**Comment by shawnmgoulet** [comment]
@jccartwright
From the Experience Builder team:

> Sorry, it's jimuHistory, instead of browserHistory, so should look like:
```jsx
\\ import
import { jimuHistory } from 'jimu-core';
\\ use
jimuHistory.changeView();
```

Please let me know if/when you're able to take a look and how it works out for you. I may have time later today.

**Comment by jccartwright** [comment]
@shawnmgoulet 
this works great - thanks for tracking it down!
