### ISSUE TITLE
settings panel doesn't show

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#24]
added new [widget](https://github.com/jccartwright/exb-widgets/tree/main/widgets/filtered-record-count) but settings panel is not displaying. Tried restarting server and client and installing in a different experience.

Can you see what I'm missing?

**Comment by shawnmgoulet** [comment]
@jccartwright all you should need to add is a `config.json` file at the root of your widget with an empty object.

I think the [documentation ](https://developers.arcgis.com/experience-builder/guide/extend-base-widget/)can be improved, but it does list it as one of a widget's files. It does not say, which I will recommend adding, that it is required.

**Comment by jccartwright** [comment]
I knew I must be overlooking something simple! thanks for catching it.
