### ISSUE TITLE
review filtered-record-count widget

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#25]
This is essentially a re-write of the datasource-record-count widget attempting to improve performance and streamline logic.

@shawnmgoulet A review of the code and design decisions would be helpful.

**Comment by shawnmgoulet** [comment]
@jccartwright understanding this is supposed to display the total & filtered record counts, how do I configure this widget (+ another widget? + the data) to review & test it with a dataSource?

I configured the widget with OOTB map & filter widgets:

https://user-images.githubusercontent.com/3179974/200634364-f2a70047-b7b7-4748-8f51-bacf6d1e7ce1.mp4

I understand the total/total & 3/total, is the 56/total expected when it occurs?

**Comment by jccartwright** [comment]
I’ll add a README but for now, it expects a configured map and feature datasource. Ideally the map contains the datasource.
To fully exercise the widget you’ll also need some way to apply a filter to the datasource, e.g. the ExB Filter widget.

The purpose of the widget is to simply display the total number of features and the number with the current map extents (and any filter criteria) applied.

You’re welcome to use the same webmap <https://noaa.maps.arcgis.com/home/item.html?id=4947595256c64673ab5136fe8b183379> and datasource <https://noaa.maps.arcgis.com/home/item.html?id=b664c55c156b4b7ea9e03d72eacfee74> that I am for testing.

**Comment by jccartwright** [comment]
general approach seems reasonable. Breaking out a few specific questions into separate issues
