### ISSUE TITLE
FeatureLayerDataSource#loadCount

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#28]
The loadCount method on [FeatureLayerDataSource](https://developers.arcgis.com/experience-builder/api-reference/jimu-core/FeatureLayerDataSource#loadCount) appears to return the number of records as filtered by the current map extent and any queryParams.
What is the relationship between this method, the [queryCount](https://developers.arcgis.com/experience-builder/api-reference/jimu-core/FeatureLayerDataSource#queryCount) method, and the [count](https://developers.arcgis.com/experience-builder/api-reference/jimu-core/FeatureLayerDataSource#count) property?

Can loadCount be relied upon to automatically take into account view extent changes and queryParams? Is there any way to pass an AbortController signal as a parameter to cancel an in-flight request?

**Comment by shawnmgoulet** [comment]
comment presumably intended for issue #27 

@jccartwright - the recommended public property to watch is the [`suspended` property](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-layers-LayerView.html#suspended). When `true`, the layer isn't visible for some reason (e.g. out of scale range, not compatible with current spatial reference).

**Comment by shawnmgoulet** [comment]
@jccartwright apologies for above. Yes, it was intended for issue 27.

For this issue (28), you can safely rely on `loadCount`. It will use all the filters applied on the data source.

Experience Builder does not yet support the cancellation/abortion of a request.

I am following up on the difference/relationship between the `loadCount` method, the `queryCount` method, and the `count` property.

**Comment by shawnmgoulet** [comment]
@jccartwright

From the ExB team:

The difference between the `loadCount` & `queryCount` methods is almost the same, with the nuance described [here](https://developers.arcgis.com/experience-builder/guide/core-concepts/data-source/).
> The difference between the load and query methods is such that load updates the records property and the status of the data source, while query queries and returns the records only.
