### ISSUE TITLE
VSCode cannot find type declarations for jimu modules - LOW PRIORITY

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#4]
When using a widget hierarchy outside "your-extensions", VSCode cannot seem to locate jimu modules, errors like:
`Cannot find module 'jimu-ui' or its corresponding type declarations.ts(2307)`

see attached screenshot. Not a priority issue but thought there might be an easy configuration issue I'm missing

<img width="1428" alt="Screen Shot 2022-08-25 at 4 53 52 PM" src="https://user-images.githubusercontent.com/918022/186783640-f144bd4e-6b68-467c-bc94-9053ed48c03d.png">

**Comment by shawnmgoulet** [comment]
![image](https://user-images.githubusercontent.com/3179974/186919281-384aceb4-a4bc-457c-8122-45667745a692.png)

hey @jccartwright - there is a PR in to update the docs for this, but to fix this, please add, in your case `"exb-widgets"` (in mine - `"ncei-exb-widgets"` in the image above) to the `.\client\tsconfig.json` file's `"include"` array. In there, you'll see that the dev edition ships with `"your-extensions"` in the `"include"` array.

**Comment by jccartwright** [comment]
Thanks - that works great!
