### ISSUE TITLE
how to pass data from DataSourceFilterChange message to widget

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#5]
Action handler, e.g. [MessageHandlerAction](https://github.com/jccartwright/exb-widgets/blob/main/widgets/subscriber-demo/src/actions/message-handler-action.ts) is receiving framework message but lacks a good way to pass that on to the [widget](https://github.com/jccartwright/exb-widgets/blob/main/widgets/subscriber-demo/src/runtime/widget.tsx) since the content of the message does not change with filter changes.

Can the datasource referenced in the message body be queried in the MessageHandlerAction to retrieve the queryParams and pass that as string?

**Comment by shawnmgoulet** [comment]
I want to state this back a bit differently to confirm above with another explanation (using `DataSourceFilterChangeMessage` as an example):

[`DataSourceFilterChangeMessage`](https://developers.arcgis.com/experience-builder/api-reference/jimu-core/DataSourceFilterChangeMessage) contains the `type`, `widgetId`, and the `dataSourceId` props.

If the `DataSource` is a `QueriableDataSource`, for instance, then an option could be to:
1. use the `dataSourceId` returned from the message to select the appropriate `DataSource`
2. invoke `QueriableDataSource.getCurrentQueryParams()` like you are doing within your `datasource-record-count` widget and is done in a few OOTB widgets

**Comment by jccartwright** [comment]
The DataSource referenced by the dataSourceId in the message is a QueriableDataSource. 

However, I'm not clear on how to construct a QueriableDataSource given that Id.

Ideally this could be done w/in the Action handler and then pass the queryParams as a string to trigger the widget's componentDidUpdate method

**Comment by jccartwright** [comment]
although I don't know if it's the best approach, I now have a working version. Using DataSourceManager to get the DataSource and ultimately the currentQueryParams and then passing that string which triggers the componentDidUpdate method.

**Comment by shawnmgoulet** [comment]
Thanks @jccartwright. This implementation was added in this commit, yes?

https://github.com/jccartwright/exb-widgets/commit/41a2ad8b39d6ba5c59cb66d0650217b9b2c07c0c

**Comment by jccartwright** [comment]
Basically yes, although I significantly improved it in more recent commits in converting to functional component and using Redux hook.

If you’ve got some time tomorrow, I can walk you through what I now have on this and the client-side layer.

**Comment by jccartwright** [comment]
please review and comment on approach used in [subscriber-demo](https://github.com/jccartwright/exb-widgets/tree/main/widgets/subscriber-demo)

**Comment by shawnmgoulet** [comment]
I think this approach, when not needing config options, is sound. I see the `DataRecordsSelectionChange` coming through in the console and the way you set it up as a functional component makes sense to me.
