### ISSUE TITLE
what is LocationChangeMessage used for?

### ISSUE THREAD

**Issue by jccartwright** [jccartwright/exb-widgets#6]
How is a LocationChangeMessage originated and what does it contain?

**Comment by shawnmgoulet** [comment]
Described within `client\jimu-core\lib\message\message-base-types.d.ts`:

> /**
 /*   The `LocationChangeMessage` uses the widget's id `widgetId`, the `MessageType` `LOCATION_CHANGE` message,
 /*   the location `point`. This message is used when a widget needs to announce its changes on location to other widgets.
 /*   For example: Map widget publishes this message when user click on the map.
 /*   Note: When user clicks on features, the map widget publishes both LocationChangeMessage and DataRecordsSelectionChangeMessage.
 /*    If use does not click on feature, the map widget publishes the LocationChangeMessage only.
 */
 
 As per above, this _may_ be evaluated/validated as a potential alternative for #9 (if a user clicks on feature(s) within a map widget, should yield both message published).
